# Generated by Django 4.0.6 on 2022-10-31 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0013_alter_event_sport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date_created',
        ),
        migrations.AddField(
            model_name='event',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
